plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'forgeflower'


dependencyResolutionManagement.versionCatalogs.register('libs') {
    plugin 'licenser',    'net.minecraftforge.licenser'    version '1.2.0'
    plugin 'gradleutils', 'net.minecraftforge.gradleutils' version '3.3.21'
    plugin 'gitversion',  'net.minecraftforge.gitversion'  version '3.1.7'
    plugin 'changelog',   'net.minecraftforge.changelog'   version '3.1.3'
    plugin 'shadow',      'com.gradleup.shadow'            version '9.2.2'
}
    
dependencyResolutionManagement.versionCatalogs.register('testLibs') {
    library 'hamcrest', 'org.hamcrest',         'hamcrest-core' version '2.2'
    library 'assertj',  'org.assertj',          'assertj-core'  version '3.15.0'
    library 'junit',    'junit',                'junit'         version '4.12'
}