package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ForgeFlower__PullRequests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ForgeFlower__PullRequests")) {
    features {
        add {
            commitStatusPublisher {
                id = "MinecraftForge_BuildWithNotifications_GithubStatusPublisher"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:22a3cc55-cbdd-470a-a1c3-53c37e116fb5"
                    }
                }
            }
        }
    }
}
