name: Publish

on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 17
      gradle_tasks: "ForgeFlower:publish"
      artifact_name: "forgeflower"
      submodules: "true"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
